# Generated by Django 3.1.5 on 2021-01-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuserApp', '0002_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidios',
            name='slug',
        ),
    ]
