# Generated by Django 3.1.5 on 2021-01-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuserApp', '0003_remove_vidios_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.TextField(max_length=999, null=True),
        ),
    ]
