# Generated by Django 3.1.5 on 2021-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuserApp', '0004_address_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img_alumni')),
                ('description', models.TextField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img_faculty')),
                ('description', models.TextField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Sosmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
    ]
